### ISSUE TITLE
wsproto docs should move to python-hyper.org

### ISSUE THREAD

**Issue by jeamland** [python-hyper/documentation#24]
I've got the docs up at wsproto.readthedocs.org but they should probably move under python-hyper.org at some point.

**Comment by Lukasa** [comment]
\o/ Ok, so getting this to work involves some dancing on RTD. To do it I'll need to be made a maintainer on the wsproto RTD so I can add it as an appropriate sub-project. Do you mind?

**Comment by Lukasa** [comment]
Hrm, actually that didn't go as planned at all.

@ericholscher, tagging you in. I just attempted to add wsproto as a subproject of hyper-documentation. RTD rightly rejected that attempt because I don't have admin on wsproto, but now visiting https://python-hyper.org/wsproto/ does in fact redirect to the wsproto docs. That...doesn't seem right. What's going on there?

**Comment by ericholscher** [comment]
@agjohnson is doing a refactor of this page today, so will call this a bug :(

**Comment by Lukasa** [comment]
@ericholscher Sounds reasonable to me. It's cool, bugs happen, and this one is pretty benign as they go.

**Comment by Kriechi** [comment]
As it turns out - I had the same idea two weeks ago: https://github.com/python-hyper/wsproto/issues/71

Any progress on this?

**Comment by Kriechi** [comment]
Done via 0b60eadb7a3e016256ebe5f541679a21a7e3c9e7
